export const majors = [
  {
    id: 'electronic-information-engineering',
    name: '电子信息工程',
    category: '理工类',
    difficulty: 4,
    difficultyText: '难度较高',
    mathRequired: true,
    englishRequired: true,
    officeWorkerFriendly: 2,
    certificateOnlyFriendly: 1,
    suitableFor: ['有理工基础', '想学技术', '不怕数学和专业课'],
    notSuitableFor: ['只想简单拿证', '数学基础差', '每天学习时间很少'],
    tags: ['理工类', '难度较高', '适合有基础'],
    intro: '电子信息工程属于理工类专业，对基础和复习时间有一定要求。适合有相关工作、专业背景，或者确实想往技术方向发展的人。',
    studyAdvice: '建议优先整理历年真题，先做题再回看知识点。主观题可以围绕关键词反复记忆，考前集中复盘高频题。',
    thesisAdvice: '论文选题不要太大，尽量结合实际应用场景，例如通信、嵌入式、物联网、前端系统、数据采集等方向。',
    personalAdvice: '如果只是想轻松拿证，不建议优先选这个专业。如果你本身做技术，或者希望学历和技术背景相关，可以考虑。',
    subjects: ['中国近现代史纲要', '马克思主义基本原理概论', '英语（二）', '专业基础课', '专业核心课', '毕业论文'],
  },
  {
    id: 'administration',
    name: '行政管理',
    category: '管理类',
    difficulty: 2,
    difficultyText: '相对容易',
    mathRequired: false,
    englishRequired: true,
    officeWorkerFriendly: 5,
    certificateOnlyFriendly: 5,
    suitableFor: ['上班族', '想尽快拿证', '不想考数学'],
    notSuitableFor: ['想学强技能', '希望专业和技术深度绑定'],
    tags: ['不考数学', '上班族友好', '拿证友好'],
    intro: '行政管理是很多自考新手会考虑的专业，整体偏记忆理解，不太依赖数学基础。',
    studyAdvice: '适合用真题 + 高频考点复习。不要一开始陷入视频课，先把考试题型和常考内容摸清楚。',
    thesisAdvice: '论文可以围绕基层治理、行政效率、公共服务、企业行政管理等方向。',
    personalAdvice: '如果目标是尽快拿证，又不想碰数学，可以优先了解这个专业。',
    subjects: ['中国近现代史纲要', '马克思主义基本原理概论', '英语（二）', '行政管理学', '公共政策', '毕业论文'],
  },
  {
    id: 'chinese-language-literature',
    name: '汉语言文学',
    category: '文史类',
    difficulty: 3,
    difficultyText: '中等',
    mathRequired: false,
    englishRequired: true,
    officeWorkerFriendly: 4,
    certificateOnlyFriendly: 4,
    suitableFor: ['文科基础较好', '喜欢阅读写作', '不想考数学'],
    notSuitableFor: ['完全不想背诵', '讨厌写作'],
    tags: ['不考数学', '文科类', '写作较多'],
    intro: '汉语言文学偏文科，通常不涉及数学，对阅读、理解和写作能力有一定要求。',
    studyAdvice: '适合通过教材重点、真题、文学常识和主观题模板来复习。主观题要多整理关键词。',
    thesisAdvice: '论文方向可以围绕文学作品分析、语言应用、语文教育、文化传播等。',
    personalAdvice: '如果你不怕背诵和写作，又想避开数学，可以考虑。',
    subjects: ['中国近现代史纲要', '马克思主义基本原理概论', '英语（二）', '中国现代文学史', '古代文学', '毕业论文'],
  },
  {
    id: 'preschool-education',
    name: '学前教育',
    category: '教育类',
    difficulty: 3,
    difficultyText: '中等',
    mathRequired: false,
    englishRequired: true,
    officeWorkerFriendly: 4,
    certificateOnlyFriendly: 3,
    suitableFor: ['教育行业从业者', '宝妈', '想从事幼教相关工作'],
    notSuitableFor: ['对教育完全没兴趣', '只想选最轻松专业'],
    tags: ['教育类', '不考数学', '适合相关从业'],
    intro: '学前教育适合对幼儿教育、教育心理、课程设计等方向感兴趣的人。',
    studyAdvice: '建议结合真题梳理教育学、心理学相关高频概念，主观题要会结合场景作答。',
    thesisAdvice: '论文可以围绕幼儿行为、家庭教育、园本课程、游戏化教学等方向。',
    personalAdvice: '如果你本身从事教育、托育、培训相关工作，这个专业的匹配度较高。',
    subjects: ['中国近现代史纲要', '马克思主义基本原理概论', '英语（二）', '学前教育原理', '学前心理学', '毕业论文'],
  },
  {
    id: 'business-administration',
    name: '工商管理',
    category: '管理类',
    difficulty: 3,
    difficultyText: '中等',
    mathRequired: false,
    englishRequired: true,
    officeWorkerFriendly: 4,
    certificateOnlyFriendly: 4,
    suitableFor: ['企业上班族', '管理岗位', '想要通用型专业'],
    notSuitableFor: ['想要非常强专业壁垒', '完全不想背概念'],
    tags: ['管理类', '通用型', '上班族友好'],
    intro: '工商管理属于通用管理类专业，适合企业上班族和想要提升学历的人。',
    studyAdvice: '适合通过真题梳理管理学、市场营销、人力资源等高频内容。',
    thesisAdvice: '论文可以围绕企业管理、绩效、营销、人力资源等实际场景。',
    personalAdvice: '如果你不知道专业怎么选，又不想太偏技术，可以把它作为备选。',
    subjects: ['中国近现代史纲要', '马克思主义基本原理概论', '英语（二）', '管理学原理', '市场营销', '毕业论文'],
  },
  {
    id: 'human-resource-management',
    name: '人力资源管理',
    category: '管理类',
    difficulty: 2,
    difficultyText: '相对容易',
    mathRequired: false,
    englishRequired: true,
    officeWorkerFriendly: 5,
    certificateOnlyFriendly: 4,
    suitableFor: ['HR从业者', '上班族', '不想考数学'],
    notSuitableFor: ['想学技术类能力', '对管理完全没兴趣'],
    tags: ['不考数学', '管理类', '上班族友好'],
    intro: '人力资源管理偏管理和实务，比较适合上班族，尤其是从事行政、人事、运营相关工作的人。',
    studyAdvice: '建议重点整理概念、流程和案例类主观题，复习时多看高频真题。',
    thesisAdvice: '论文方向可以围绕招聘、培训、绩效、薪酬、员工关系等。',
    personalAdvice: '如果你希望专业和职场通用能力相关，这个专业可以考虑。',
    subjects: ['中国近现代史纲要', '马克思主义基本原理概论', '英语（二）', '人力资源管理', '劳动关系', '毕业论文'],
  },
]

export function getMajorById(id) {
  return majors.find((item) => item.id === id)
}
