export const resources = [
  {
    id: 'degree-condition-checklist',
    name: '学位证条件自查表',
    type: '自查清单',
    stage: '学位自查',
    audience: '本科且可能需要学位证的人',
    desc: '核对平均分、论文成绩、学位英语、申请期限等常见要求。',
    method: '先看毕业学位工具',
    path: '/graduation',
    tags: ['学位证', '自查', '申请条件'],
  },
  {
    id: 'study-node-checklist',
    name: '复习节点清单',
    type: '备考清单',
    stage: '复习备考',
    audience: '准备安排统考、省考复习节奏的人',
    desc: '围绕真题、错题、教材、冲刺、考前检查等节点安排复习。',
    method: '先生成复习计划',
    path: '/study-plan',
    tags: ['复习', '节点', '考前准备'],
  },
  {
    id: 'thesis-starter-checklist',
    name: '小自考本科论文入门清单',
    type: '论文清单',
    stage: '论文入门',
    audience: '第一次写小自考本科论文的人',
    desc: '按选题、提纲、格式、查重、答辩和成绩归档等关键节点准备。',
    method: '先用论文规划器',
    path: '/thesis',
    tags: ['论文', '小自考本科', '答辩准备'],
  },
]
